## Array Computing

In [1]:
myList = [1, 2]
myTuple = (3,4)

print("List has square brackets: {}".format(myList))
print("Tuple has regular brackets: {}".format(myTuple))

List has square brackets: [1, 2]
Tuple has regular brackets: (3, 4)


### Mathematical Operations on Vectors

In [2]:
numList  = [0.0, 1.0, 2.0]
print(2 * numList)

[0.0, 1.0, 2.0, 0.0, 1.0, 2.0]


In [3]:
numTuple = (0.0, 1.0, 2.0)
print(2 * numTuple)

(0.0, 1.0, 2.0, 0.0, 1.0, 2.0)


In [4]:
print(2.0 * numList)

TypeError: can't multiply sequence by non-int of type 'float'

We can compute the distance of an object, given its time and acceleration: $y=\frac{1}{2}at^2$

In [5]:
def distance(t, a = 9.8):
    '''Calculate the distance given a time and acceleration.
       
       Input:  time in seconds <int> or <float>,
               acceleration in m/s^2 <int> or <float>
       Output: distance in m <float>
    '''
    return 0.5 * a * t**2


One way to calculate the distance for many different times is to use lists.  We can create a list of 'times' by using 'range' and then through a list comprehension and a for loop, run that list through our 'distance' function and generate a 'distance' list. 

In [6]:
# filling a time list with values 0-10, and calculating the distances.
timeList = [i for i in range(11)]
distList = [distance(t) for t in timeList]
print("Time List:    ", timeList)
print("Distance List:", distList)

Time List:     [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Distance List: [0.0, 4.9, 19.6, 44.1, 78.4, 122.50000000000001, 176.4, 240.10000000000002, 313.6, 396.90000000000003, 490.00000000000006]


Not exaclty a favorable output format.  Let's make it look more readable.  We want our output to be as well formated as a table with t and d values. 

Read on your own about "stitching results together."

One way to do this is to make a new list that has both time and distance values and then print the elements of that list through a for loop. 

In [7]:
timeDistList = []

print("Time  Distance")

for i in range(11):
    timeDistList.append([timeList[i], distList[i]])

for element in timeDistList:
    print(element)

Time  Distance
[0, 0.0]
[1, 4.9]
[2, 19.6]
[3, 44.1]
[4, 78.4]
[5, 122.50000000000001]
[6, 176.4]
[7, 240.10000000000002]
[8, 313.6]
[9, 396.90000000000003]
[10, 490.00000000000006]


One can do this more compactly with the command "zip". Notice that the output gives us tuples. 

In [8]:
for element in zip(timeList, distList):
    print(element)

(0, 0.0)
(1, 4.9)
(2, 19.6)
(3, 44.1)
(4, 78.4)
(5, 122.50000000000001)
(6, 176.4)
(7, 240.10000000000002)
(8, 313.6)
(9, 396.90000000000003)
(10, 490.00000000000006)


"zip" can also be used with lists.

In [9]:
# with list comprehension (making a list)
timeDistList2 = [[time, dist] for time, dist in zip(timeList, distList)]
print("Time  Distance")

for element in timeDistList2:
    print(element)

Time  Distance
[0, 0.0]
[1, 4.9]
[2, 19.6]
[3, 44.1]
[4, 78.4]
[5, 122.50000000000001]
[6, 176.4]
[7, 240.10000000000002]
[8, 313.6]
[9, 396.90000000000003]
[10, 490.00000000000006]


### Basics of numpy arrays

Let's take a list and convert it into an array.
Note that you must first import numpy.

In [10]:
import numpy as np

myList  = [1, 2, 3]
myArray = np.array(myList)

print(type(myArray))   #did the conversion to an array work?
print(myArray)

<class 'numpy.ndarray'>
[1 2 3]


To create an array of length n=10 filled with zeros:

In [11]:
myArray = np.zeros(10)
print(myArray)

# np.zeros also has a data type.  If we wanted 10 integers, we can specify
# myArray = np.zeros(10, dtype=int)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


We often want an array with specific number of elements.

`numpy.linspace(start, end, number of elements)` does this:

NOTE:  the "end" value is NOT (end - 1)

In [12]:
zArray = np.linspace(0, 5, 6)
print(zArray)

[0. 1. 2. 3. 4. 5.]


We often want array elements equally spaced by some interval (delta).  

`numpy.arange(start, end, step size)` does this:

NOTE: the "end" value is (end - step size)


In [13]:
print(np.arange(6))
print(np.arange(0,6,0.5))

[0 1 2 3 4 5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]


### Accessing elements inside of arrays, slicing, and editing arrays

Array elements are accessed with square brackets, the same as lists:

In [14]:
print(zArray)
print(zArray[3])

[0. 1. 2. 3. 4. 5.]
3.0


Slicing can also be done on arrays:

In [15]:
yArray = zArray[1:4]
print(yArray)

[1. 2. 3.]


Next, let's edit one of the values in the z array

In [16]:
zArray[3] = 10.0

print(zArray)

[ 0.  1.  2. 10.  4.  5.]


Did this change the values in yArray, which we made a slice of the zArray?

In [17]:
print(yArray)

[ 1.  2. 10.]


Yikes, it did change it!!!

The variable yArray is a **reference** to three elements (a slice) from zArray: element indices 1, 2, and 3.

Here is a blog post which discusses this issue nicely:

http://nedbatchelder.com/text/names.html

If we use lists, this doesn't happen.  We can change an element inside of a sublist, but the main list won't change. 

In [18]:
lList = [1, 2, 3]
mList = lList[1:2]

print(mList)
lList[1] = 10
print(mList)

[2]
[2]


Do not forget this -- check your array values frequently if you are unsure!

How can we avoid the problem of automatically changing a sub-array when we change the main array or vice versa? 

This can be done by creating an independent copy of an array!

In [16]:
yArray2 = yArray.copy()
print(yArray,yArray2)

yArray2[1] = 3.5
print(yArray,yArray2) 

# Notice that yArray was not changed when yArray2 was, 
# since yArray2 was created using the .copy() method.

[ 1.  2. 10.] [ 1.  2. 10.]
[ 1.  2. 10.] [ 1.   3.5 10. ]


## Computing with Arrays

Let's go back to our function that calculates distance when time, t, and acceleration are given.

In [20]:
def distance(t, a = 9.8):
    '''Calculate the distance given a time and acceleration.
       
       Input:  time in seconds <int> or <float>,
               acceleration in m/s^2 <int> or <float>
       Output: distance in m <float>
    '''
    return 0.5 * a * t**2

We can create a list of the times and run it through the function to get the distances. The two resulting lists can then be converted to arrays!
To convert a list to an array, we must import numpy and use `np.array` command.

In [21]:
timeList = [i for i in range(11)]            # Create the time list
distList = [distance(t) for t in timeList]   # Create the distance list

# convert the two lists into arrays
timeArray = np.array(timeList)
distArray = np.array(distList)

# print the arrays
print(type(timeArray), timeArray)
print(type(distArray), distArray)

<class 'numpy.ndarray'> [ 0  1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'> [  0.    4.9  19.6  44.1  78.4 122.5 176.4 240.1 313.6 396.9 490. ]


We can do this directly by creating arrays (without converting from a list) with `np.linspace` to create timeArray and `np.zeros` to create distArray.

(This is merely a demonstration, not superior to the above code.)

In [20]:
timeArray = np.linspace(0, 10, 11)  # Create the time array
distArray = np.zeros(11)            # Create the distance array populated with 0's

print("Time Array:          ", type(timeArray), timeArray)
print("Dist Array Zeros:    ", type(distArray), distArray)

for i in range(11):
    distArray[i] = distance(timeArray[i])   # Populate the distance array with calculated values

print("Dist Array Populated:", type(distArray), distArray)

Time Array:           <class 'numpy.ndarray'> [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Dist Array Zeros:     <class 'numpy.ndarray'> [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dist Array Populated: <class 'numpy.ndarray'> [  0.    4.9  19.6  44.1  78.4 122.5 176.4 240.1 313.6 396.9 490. ]


### Vectorization -- one of the great powers of arrays

The examples above are great, but they don't use the computation power of arrays by operating on all the elements simultaneously!

**Loops are slow**.
Operating on the elements simultaneously is much faster (and simpler!).

"Vectorization" is replacing a loop with vector or array expressions.

In [21]:
timeArray = np.linspace(0, 10, 11)   # Create the time array
distArray = distance(timeArray)      # Create and populate the distance array using vectorization

print("Time Array:", type(timeArray), timeArray)
print("Dist Array:", type(distArray), distArray)

Time Array: <class 'numpy.ndarray'> [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Dist Array: <class 'numpy.ndarray'> [  0.    4.9  19.6  44.1  78.4 122.5 176.4 240.1 313.6 396.9 490. ]


When we use arrays, we can calculate the same equation:

$y=\frac{1}{2}at^2$ 

by doing the calculation directly on the arrays.

In [23]:
a = 9.8   # acceleration due to gravity

timeArray = np.linspace(0, 10, 11)  # create the time array

distArray = 0.5 * a * timeArray**2  # directly calculate the distance

print(timeArray)
print(distArray)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[  0.    4.9  19.6  44.1  78.4 122.5 176.4 240.1 313.6 396.9 490. ]


Caution: numpy has its own math functions, such as sin, cos, pi, exp, and some of these are slightly different from Python's math module.

(Also, the math module does not accept numpy array arguments.)

Extras:

Python names and references:

http://nedbatchelder.com/text/names.html

Generators:

https://www.jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/
