# Multi-Dimensional Arrays

Standard matrix notation is $A_{i,j}$, where i and j are
the row and column numbers, respectively.

Read $A_{i,j}$ as "A-sub-i-sub-j" or "A-sub-i-j".
Commas are often not used in the subscripts or
have different meanings.
 
In standard mathematics, the indexing starts with 1.

In Python, the indexing starts with 0.


Matrices (arrays) can have an arbitrary number of dimensions.

The number of dimensions is the "rank".

#### Q. What is the rank of $A_{i,j,k,l}$?

The shape of an array is a $d$-vector (or 1-D array) that holds the number of elements in each dimension. $d$ represents the dimensionality of the array.

E.g., the shape of a $A_{i,j,k,l}$ is ($n_i$, $n_j$, $n_k$, $n_l$), where n denotes the number of elements in dimensions $i$, $j$, $k$, and $l$.

### Two-Dimensional Numerical Python Arrays

A 2-D array is a matrix, and is analogous to an array of arrays, though each element of an array must have the same data type.

Example:  $\lambda = \frac{c}{f}$

where $\lambda$ is wavelength in meters, 
speed of light, $c = 3.00 \cdot 10^8$ m/s, 
and $f$ is frequency in Hz.

In [1]:
import numpy as np
c = 3.0e8

# Create a wavelength array (in mm; close to 
# the peak of the cosmic microwave background radiation = 1.9 mm):

waveArray = np.linspace(1.0, 3.0, 21)
print(waveArray)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3. ]


In [2]:
# Now, convert to frequency 
# (note conversion from mm to m):

freqArray = c / (waveArray / 1e3)
print(freqArray)

[3.00000000e+11 2.72727273e+11 2.50000000e+11 2.30769231e+11
 2.14285714e+11 2.00000000e+11 1.87500000e+11 1.76470588e+11
 1.66666667e+11 1.57894737e+11 1.50000000e+11 1.42857143e+11
 1.36363636e+11 1.30434783e+11 1.25000000e+11 1.20000000e+11
 1.15384615e+11 1.11111111e+11 1.07142857e+11 1.03448276e+11
 1.00000000e+11]


### Make a table with pairs of wavelength and frequency

In [3]:
table = [[wavelength, frequency] for wavelength, frequency in zip(waveArray, freqArray)]

for row in table:
    print(row)

[1.0, 300000000000.0]
[1.1, 272727272727.2727]
[1.2, 250000000000.00003]
[1.3, 230769230769.23077]
[1.4, 214285714285.7143]
[1.5, 200000000000.0]
[1.6, 187500000000.0]
[1.7000000000000002, 176470588235.2941]
[1.8, 166666666666.66666]
[1.9, 157894736842.10526]
[2.0, 150000000000.0]
[2.1, 142857142857.14282]
[2.2, 136363636363.63635]
[2.3, 130434782608.69565]
[2.4000000000000004, 124999999999.99998]
[2.5, 120000000000.0]
[2.6, 115384615384.61539]
[2.7, 111111111111.1111]
[2.8, 107142857142.85715]
[2.9000000000000004, 103448275862.06895]
[3.0, 100000000000.0]


In [4]:
# or with arrays
table = np.array([waveArray, freqArray])
print(table)

[[1.00000000e+00 1.10000000e+00 1.20000000e+00 1.30000000e+00
  1.40000000e+00 1.50000000e+00 1.60000000e+00 1.70000000e+00
  1.80000000e+00 1.90000000e+00 2.00000000e+00 2.10000000e+00
  2.20000000e+00 2.30000000e+00 2.40000000e+00 2.50000000e+00
  2.60000000e+00 2.70000000e+00 2.80000000e+00 2.90000000e+00
  3.00000000e+00]
 [3.00000000e+11 2.72727273e+11 2.50000000e+11 2.30769231e+11
  2.14285714e+11 2.00000000e+11 1.87500000e+11 1.76470588e+11
  1.66666667e+11 1.57894737e+11 1.50000000e+11 1.42857143e+11
  1.36363636e+11 1.30434783e+11 1.25000000e+11 1.20000000e+11
  1.15384615e+11 1.11111111e+11 1.07142857e+11 1.03448276e+11
  1.00000000e+11]]


This isn't quite what we had above nor is it a good table. Instead of (wavelength, frequency) pairs, all wavelengths are in one sub-array, and all the frequencies in another. The table is column major now. Meaning that the first row has all the values of wavelength, and the 2nd row has all the values of frequency. This is not intuitive.  We would prefer to have each row show the wavelength and the corresponding frequency. 

#### Q. How could we regroup elements to match the previous incarnation? (row major)

In [5]:
table.T  # table.T is the transpose of table.

array([[1.00000000e+00, 3.00000000e+11],
       [1.10000000e+00, 2.72727273e+11],
       [1.20000000e+00, 2.50000000e+11],
       [1.30000000e+00, 2.30769231e+11],
       [1.40000000e+00, 2.14285714e+11],
       [1.50000000e+00, 2.00000000e+11],
       [1.60000000e+00, 1.87500000e+11],
       [1.70000000e+00, 1.76470588e+11],
       [1.80000000e+00, 1.66666667e+11],
       [1.90000000e+00, 1.57894737e+11],
       [2.00000000e+00, 1.50000000e+11],
       [2.10000000e+00, 1.42857143e+11],
       [2.20000000e+00, 1.36363636e+11],
       [2.30000000e+00, 1.30434783e+11],
       [2.40000000e+00, 1.25000000e+11],
       [2.50000000e+00, 1.20000000e+11],
       [2.60000000e+00, 1.15384615e+11],
       [2.70000000e+00, 1.11111111e+11],
       [2.80000000e+00, 1.07142857e+11],
       [2.90000000e+00, 1.03448276e+11],
       [3.00000000e+00, 1.00000000e+11]])

In [6]:
# let's just work with the transpose

table = table.T 

#### Q. What should this yield?

In [7]:
table.shape

(21, 2)

In [8]:
# 20th row, 1st column
table[20][0]

3.0

In [9]:
table[20,0]

3.0

In [10]:
# just so we can see the table
table

array([[1.00000000e+00, 3.00000000e+11],
       [1.10000000e+00, 2.72727273e+11],
       [1.20000000e+00, 2.50000000e+11],
       [1.30000000e+00, 2.30769231e+11],
       [1.40000000e+00, 2.14285714e+11],
       [1.50000000e+00, 2.00000000e+11],
       [1.60000000e+00, 1.87500000e+11],
       [1.70000000e+00, 1.76470588e+11],
       [1.80000000e+00, 1.66666667e+11],
       [1.90000000e+00, 1.57894737e+11],
       [2.00000000e+00, 1.50000000e+11],
       [2.10000000e+00, 1.42857143e+11],
       [2.20000000e+00, 1.36363636e+11],
       [2.30000000e+00, 1.30434783e+11],
       [2.40000000e+00, 1.25000000e+11],
       [2.50000000e+00, 1.20000000e+11],
       [2.60000000e+00, 1.15384615e+11],
       [2.70000000e+00, 1.11111111e+11],
       [2.80000000e+00, 1.07142857e+11],
       [2.90000000e+00, 1.03448276e+11],
       [3.00000000e+00, 1.00000000e+11]])

In [11]:
for index1 in range(table.shape[0]):

    # Q. What is table.shape[0]?
    
    for index2 in range(table.shape[1]):
        print('table[{},{}] = {:g}'.format(index1, index2, table[index1, index2]))
        # Q. What will this loop print?
        

table[0,0] = 1
table[0,1] = 3e+11
table[1,0] = 1.1
table[1,1] = 2.72727e+11
table[2,0] = 1.2
table[2,1] = 2.5e+11
table[3,0] = 1.3
table[3,1] = 2.30769e+11
table[4,0] = 1.4
table[4,1] = 2.14286e+11
table[5,0] = 1.5
table[5,1] = 2e+11
table[6,0] = 1.6
table[6,1] = 1.875e+11
table[7,0] = 1.7
table[7,1] = 1.76471e+11
table[8,0] = 1.8
table[8,1] = 1.66667e+11
table[9,0] = 1.9
table[9,1] = 1.57895e+11
table[10,0] = 2
table[10,1] = 1.5e+11
table[11,0] = 2.1
table[11,1] = 1.42857e+11
table[12,0] = 2.2
table[12,1] = 1.36364e+11
table[13,0] = 2.3
table[13,1] = 1.30435e+11
table[14,0] = 2.4
table[14,1] = 1.25e+11
table[15,0] = 2.5
table[15,1] = 1.2e+11
table[16,0] = 2.6
table[16,1] = 1.15385e+11
table[17,0] = 2.7
table[17,1] = 1.11111e+11
table[18,0] = 2.8
table[18,1] = 1.07143e+11
table[19,0] = 2.9
table[19,1] = 1.03448e+11
table[20,0] = 3
table[20,1] = 1e+11


In [12]:
# a reminder of what this looked like with lists:
alist =[1.0,2.0,3.0]
for i in enumerate(alist):
    print(i)

(0, 1.0)
(1, 2.0)
(2, 3.0)


In [13]:
for index_tuple, value in np.ndenumerate(table):
    print('index {} has value {:.2e}'.format(index_tuple, value))

index (0, 0) has value 1.00e+00
index (0, 1) has value 3.00e+11
index (1, 0) has value 1.10e+00
index (1, 1) has value 2.73e+11
index (2, 0) has value 1.20e+00
index (2, 1) has value 2.50e+11
index (3, 0) has value 1.30e+00
index (3, 1) has value 2.31e+11
index (4, 0) has value 1.40e+00
index (4, 1) has value 2.14e+11
index (5, 0) has value 1.50e+00
index (5, 1) has value 2.00e+11
index (6, 0) has value 1.60e+00
index (6, 1) has value 1.88e+11
index (7, 0) has value 1.70e+00
index (7, 1) has value 1.76e+11
index (8, 0) has value 1.80e+00
index (8, 1) has value 1.67e+11
index (9, 0) has value 1.90e+00
index (9, 1) has value 1.58e+11
index (10, 0) has value 2.00e+00
index (10, 1) has value 1.50e+11
index (11, 0) has value 2.10e+00
index (11, 1) has value 1.43e+11
index (12, 0) has value 2.20e+00
index (12, 1) has value 1.36e+11
index (13, 0) has value 2.30e+00
index (13, 1) has value 1.30e+11
index (14, 0) has value 2.40e+00
index (14, 1) has value 1.25e+11
index (15, 0) has value 2.50e+

In [14]:
print(table.shape)
print(type(table.shape))

(21, 2)
<class 'tuple'>


## Slicing nD Arrays

In [15]:
print(table)

[[1.00000000e+00 3.00000000e+11]
 [1.10000000e+00 2.72727273e+11]
 [1.20000000e+00 2.50000000e+11]
 [1.30000000e+00 2.30769231e+11]
 [1.40000000e+00 2.14285714e+11]
 [1.50000000e+00 2.00000000e+11]
 [1.60000000e+00 1.87500000e+11]
 [1.70000000e+00 1.76470588e+11]
 [1.80000000e+00 1.66666667e+11]
 [1.90000000e+00 1.57894737e+11]
 [2.00000000e+00 1.50000000e+11]
 [2.10000000e+00 1.42857143e+11]
 [2.20000000e+00 1.36363636e+11]
 [2.30000000e+00 1.30434783e+11]
 [2.40000000e+00 1.25000000e+11]
 [2.50000000e+00 1.20000000e+11]
 [2.60000000e+00 1.15384615e+11]
 [2.70000000e+00 1.11111111e+11]
 [2.80000000e+00 1.07142857e+11]
 [2.90000000e+00 1.03448276e+11]
 [3.00000000e+00 1.00000000e+11]]


In [16]:
# this will print the 1st column only:
print(table[0:, 0])
# or
# print(table[:, 0])

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3. ]


In [17]:
# This will print the second column:

print(table[:, 1])

[3.00000000e+11 2.72727273e+11 2.50000000e+11 2.30769231e+11
 2.14285714e+11 2.00000000e+11 1.87500000e+11 1.76470588e+11
 1.66666667e+11 1.57894737e+11 1.50000000e+11 1.42857143e+11
 1.36363636e+11 1.30434783e+11 1.25000000e+11 1.20000000e+11
 1.15384615e+11 1.11111111e+11 1.07142857e+11 1.03448276e+11
 1.00000000e+11]


In [18]:
# this prints the entire table
print(table[0:]) 
# so does
# print(table[:]) 

[[1.00000000e+00 3.00000000e+11]
 [1.10000000e+00 2.72727273e+11]
 [1.20000000e+00 2.50000000e+11]
 [1.30000000e+00 2.30769231e+11]
 [1.40000000e+00 2.14285714e+11]
 [1.50000000e+00 2.00000000e+11]
 [1.60000000e+00 1.87500000e+11]
 [1.70000000e+00 1.76470588e+11]
 [1.80000000e+00 1.66666667e+11]
 [1.90000000e+00 1.57894737e+11]
 [2.00000000e+00 1.50000000e+11]
 [2.10000000e+00 1.42857143e+11]
 [2.20000000e+00 1.36363636e+11]
 [2.30000000e+00 1.30434783e+11]
 [2.40000000e+00 1.25000000e+11]
 [2.50000000e+00 1.20000000e+11]
 [2.60000000e+00 1.15384615e+11]
 [2.70000000e+00 1.11111111e+11]
 [2.80000000e+00 1.07142857e+11]
 [2.90000000e+00 1.03448276e+11]
 [3.00000000e+00 1.00000000e+11]]


In [19]:
# When we wanted to print the 1st column we did:
# print(table[0:, 0]) 

# Note that the following is different from what we had before: 

print(table[0:][0])

[1.e+00 3.e+11]


In [20]:
# To get the first five rows of the table:

print(table[0:5, :])

print()

# Same as:
print(table[0:5])

[[1.00000000e+00 3.00000000e+11]
 [1.10000000e+00 2.72727273e+11]
 [1.20000000e+00 2.50000000e+11]
 [1.30000000e+00 2.30769231e+11]
 [1.40000000e+00 2.14285714e+11]]

[[1.00000000e+00 3.00000000e+11]
 [1.10000000e+00 2.72727273e+11]
 [1.20000000e+00 2.50000000e+11]
 [1.30000000e+00 2.30769231e+11]
 [1.40000000e+00 2.14285714e+11]]


### Shape, Rank, Dimension

In [21]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
print(x.shape)
print(np.ndim(x))  #ndim tells us the rank

(4, 3)
2


In [23]:
# Let's say we needed to transpose this matrix
xT = x.T
print(xT)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [24]:
print(xT.shape)
print(np.ndim(xT))  #ndim tells us the rank

(3, 4)
2


In [25]:
print(xT[1,0])
print(xT[2][1])
print(xT[2,1])

2
6
6


### We can access x and y index information using numpy.indices:

In [26]:
print(xT)
print("--------------------")
print(np.indices(xT.shape))
print("--------------------")

for i in range(len(xT)):
    for j in range(len(xT[0])):
        print(i, j)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
--------------------
[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]
--------------------
0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3


In [27]:
i, j = np.indices(xT.shape)
print(i)
print(j)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


### reshape command on arrays

In [28]:
# Make a 1D
aArray = np.arange(10)
print(aArray)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
bArray = np.reshape(aArray, (2, 5))   # Make it a 2-D array, with dimensions 2x5
print(bArray)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [30]:
print(bArray.shape, bArray.size, bArray.ndim)

(2, 5) 10 2


In [31]:
# We access elements in the same way we would for 1-D arrays, except we must pass 
# more indices. For example,
print(bArray[0,0])  # First row, first column
print(bArray[0,3])  # First row, fourth column
# or equivalently,
print(bArray[0][3])

0
3
3


In [32]:
# Now instead of providing the number of elements,
# we provide the dimensions as a list or tuple
# Fill a 2 x 2 matrix with 1s
cArray = np.ones([2, 2])
print(cArray)

[[1. 1.]
 [1. 1.]]


### Array arithmetic, array functions

Multiplying an array by a number multiplies each element by that number:

In [33]:
aArray = np.linspace(0, 4, 5)  # Make an array
bArray = 2 * aArray            # Make another one, elements 2x values in a
print(aArray, bArray)          # Verify values

[0. 1. 2. 3. 4.] [0. 2. 4. 6. 8.]


We can also multiply arrays by other arrays, provided that they have the same number of elements. This is not the same as a dot product!

In [34]:
print(aArray * bArray) # NOT a dot product - multiplies element-wise

[ 0.  2.  8. 18. 32.]


In [35]:
print(aArray * aArray) # i.e. multiply an array by itself
# or instead:
print(aArray**2) 

[ 0.  1.  4.  9. 16.]
[ 0.  1.  4.  9. 16.]


In [36]:
# Each element of c is the sum of
# the corresponding elements in a and b
cArray = aArray + bArray
print(cArray)

[ 0.  3.  6.  9. 12.]


While math.sqrt could only operate on integers or floats, numpy.sqrt can operate on arrays.
The same goes for numpy.exp, numpy.sin, numpy.cos, numpy.log10, etc.

In [37]:
# Computes square root of all elements, returns as array
print(np.sqrt(cArray)) 

[0.         1.73205081 2.44948974 3.         3.46410162]


### Question

In [38]:
aArray = np.zeros(3)
for index1 in range(len(aArray)):
    for index2 in range(index1, index1 + 3):
        aArray[index1] += index2
        print(index1,index2,aArray)
         #### CHECKPOINT ####            

0 0 [0. 0. 0.]
0 1 [1. 0. 0.]
0 2 [3. 0. 0.]
1 1 [3. 1. 0.]
1 2 [3. 3. 0.]
1 3 [3. 6. 0.]
2 2 [3. 6. 2.]
2 3 [3. 6. 5.]
2 4 [3. 6. 9.]
